[versions]
agp = "9.1.0"
activity = "1.13.0"
appcompat = "1.7.1"
core = "1.18.0"
lifecycle = "2.10.0"
material = "1.13.0"
recyclerview = "1.4.0"
room = "2.8.4"
zxing = "3.5.4"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
junit = { module = "junit:junit", version = "4.13.2" }
material = { module = "com.google.android.material:material", version.ref = "material" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
